### PR TITLE
Style changes, without this the buttons were not clickable nor visible. 

### PR DESCRIPTION
**Pull request by Visgean**
Tried at firefox

### CODE REVIEW

**Comment by lamby** [comment]
Can you provide a screenshot of what you see?

(The patch is incomplete as it leaves a bunch of unused CSS around anyway)

**Comment by Visgean** [comment]
I have set one of the button with the firebug, it looks like this: https://dl.dropbox.com/s/d7bkttejixdaujr/Sn%C3%ADmek%20obrazovky.png (the mouse is on the changed user)

**Comment by lamby** [comment]
Do you have any other styling on the page that could be interfering? (You can see this in Firebug too.)

**Comment by Visgean** [comment]
Well yes, I have found some css class login...

**Comment by lamby** [comment]
I'm not sure what we can do about that on this end, save doing a full CSS reset on each of the elements added which seems like total overkill.

**Comment by Visgean** [comment]
Well I would suggest to use different names for the login class - it´s rather obvious that many other projects are using this name to refer to their own styles.

**Comment by lamby** [comment]
I've removed the login class and made the CSS apply in a different way. Thanks for the report.

**Pull request closed without merging**
