### PR TITLE
Adding new debug setting to allow the use of the user panel when DEBUG is False

### PR DESCRIPTION
**Pull request by dstegelman**
Adding this new setting allows for users to set their own preference for using the toolbar when DEBUG = False without having to set DEBUG to True.

### CODE REVIEW

**Comment by lamby** [comment]
Actually, shouldn't the settings check be:

```
getattr(settings, 'DEBUG_TOOLBAR_USER_DEBUG', settings.DEBUG)
```

.. otherwise it's always disabled unless you set DEBUG_TOOLBAR_USER_DEBUG everywhere, breaking it for the usual use-case.

**Comment by lamby** [comment]
(OOI why do you want to use this in production?)

**Comment by dstegelman** [comment]
You are correct with the default to settings.DEBUG.

Its helpful for my team to be able to login as another user with different roles in production to debug problems.

**Comment by lamby** [comment]
Ah, and you've modified debug_toolbar itself to prevent just anybody doing that?

**Comment by lamby** [comment]
Anyway, again, if you could just make one commit to do this that would be great (or I can just make the commit myself but you lose git-level attribution).

**Comment by dstegelman** [comment]
Yes, we modify debug toolbar to check for super user or staff member status before showing it.

How do I do that, or do I need to just open a new pull request?

**Comment by lamby** [comment]
> How do I do that, or do I need to just open a new pull request?

Maybe. Unless you have some extra buttons to delete stuff when you view this pull request (as you opened it).

Perhaps everyone else is less OCD about their git history... :)

**Comment by dstegelman** [comment]
Opening a new request with a single commit.

**Pull request closed without merging**
