### PR TITLE
Add new debug constant, so that users can use the toolbar in production ...

### PR DESCRIPTION
**Pull request by dstegelman**
Adding this new setting allows for users to set their own preference for using the toolbar when DEBUG = False without having to set DEBUG to True.

### CODE REVIEW

**Comment by lamby** [comment]
First, please just provide a single working commit, not two commits where one fixes the other.. 

Secondly, there is no need to edit django.conf.settings dynamically; that's actually pretty unreliable and causes weird side-effects - why not add a local app_settings.py?

**Comment by dstegelman** [comment]
Okay, would a `getattr` be acceptable for the settings:

```
getattr(settings, 'DEBUG_TOOLBAR_USER_DEBUG', False)
```

**Comment by lamby** [comment]
yes

**Comment by dstegelman** [comment]
Sorry, I'm just going to make a new pull request.

**Pull request closed without merging**
